{% set name = "pyperclip" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 180c8346b1186921c75dfd14d9048a6b5d46bfc499778811952c6dd6eb1ca6be

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - __linux  # [linux]
    - __osx  # [osx]
    - __win  # [win]
    - xclip  # [linux]
    - xsel  # [linux]
    - pyobjc-framework-cocoa  # [osx]

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyperclip

about:
  home: https://github.com/asweigart/pyperclip
  license_file: LICENSE.txt
  license: BSD-3-Clause
  license_family: BSD
  summary: A cross-platform clipboard module for Python. (only handles plain text for now)
  dev_url: https://github.com/asweigart/pyperclip
  doc_url: https://pyperclip.readthedocs.io

extra:
  recipe-maintainers:
    - jan-janssen
    - ehfd
