{% set name = "pyperclip" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7de0142ddc81bfc5c7507eea19da920b92252b548b96186caf94a5e2527d310

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - __linux  # [linux]
    - __osx  # [osx]
    - __win  # [win]
    - xclip  # [linux]
    - xsel  # [linux]
    - pyobjc-framework-cocoa  # [osx]

test:
  imports:
    - pyperclip

about:
  home: https://github.com/asweigart/pyperclip
  license_file: LICENSE.txt
  license: BSD-3-Clause
  license_family: BSD
  summary: A cross-platform clipboard module for Python. (only handles plain text for now)
  dev_url: https://github.com/asweigart/pyperclip
  doc_url: https://pyperclip.readthedocs.io

extra:
  recipe-maintainers:
    - jan-janssen
    - ehfd
