{% set name = "pyperclip" %}
{% set version = "1.6.5" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "406bc020d4b8e60d8673876271b815befc4c02fd8d919e4aacc667d69fab99ea" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - pyperclip

about:
  home: https://github.com/asweigart/pyperclip
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  license: BSD 3-Clause
  license_family: BSD
  summary: 'A cross-platform clipboard module for Python. (only handles plain text for now)'
  dev_url: https://github.com/asweigart/pyperclip
  doc_url: https://pyperclip.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
